### PR TITLE
Migrate to CircleCI

### PR DESCRIPTION
**Pull request by adrw**

### CODE REVIEW

**Comment by wesleyk** [comment]
are you keeping travis around for now?

**Comment by wesleyk** [comment]
also: looks like the circleci build isn't hooked into PRs

**Comment by adrw** [comment]
Yeah, need to remember how to hook it into the PRs. Will remove travis in a follow up PR (want to confirm pass = pass).

**Comment by wesleyk** [comment]
also: try a breaking build on circle-ci as well :-)

**Pull request merged**
